// Generated by Wrangler by running `wrangler types --x-include-runtime`

interface Env extends Env {
	KV: KVNamespace;
	UNBOUND_SEND: SendEmail;
	SPECIFIC_SEND: SendEmail;
	LIST_SEND: SendEmail;
	// AI: Ai;
}
